name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build
      run: |
        npm install
        npx hexo g
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        branch: gh-pages
        folder: public
      env:
        ACCESS_TOKEN: ${{ secrets.KEYS }}
        BASE_BRANCH: master